DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'assessment'
          AND table_name = 'assessment_result'
          AND column_name = 'assessment_result_id'
          AND is_identity = 'YES'
    ) THEN
ALTER TABLE assessment.assessment_result
ALTER COLUMN assessment_result_id
        ADD GENERATED BY DEFAULT AS IDENTITY;
END IF;
END $$;