<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Assessment\Assessments\Validations\" />
      <Folder Include="Assessment\Competencies\Validations\" />
      <Folder Include="Assessment\Templates\Validations\" />
      <Folder Include="Export\" />
      <Folder Include="UserManagement\Validations\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CompetenceAssessment.Core\CompetenceAssessment.Core.csproj" />
    </ItemGroup>

</Project>
