<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="UserManagement\Validations\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CompetenceAssessment.Core\CompetenceAssessment.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Notifications\Templates\AssessmentCompletion.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Notifications\Templates\AssessmentReviewing.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Notifications\Templates\AssessmentStart.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
