<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Assessment\Assessments\Models\" />
      <Folder Include="Assessment\Competencies\Models\" />
      <Folder Include="Assessment\Templates\Models\" />
      <Folder Include="Export\" />
      <Folder Include="UserManagement\Models\" />
    </ItemGroup>

</Project>
