<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CompetenceAssessment.Application\CompetenceAssessment.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentMigrator" Version="8.0.1" />
      <PackageReference Include="FluentMigrator.Runner.Postgres" Version="8.0.1" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.15" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.15">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Configuration">
        <HintPath>..\..\..\..\..\usr\local\share\dotnet\shared\Microsoft.AspNetCore.App\9.0.12\Microsoft.Extensions.Configuration.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <None Update="Database\Sql\20260326_2000_CreateDatabase.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Database\Sql\20260327_1100_InsertTaskType.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Database\Sql\20260331_2100_InsertTemplateType.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Database\Sql\20260331_2105_InsertScale.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Database\Sql\20260401_0900_InsertAssessmentType.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Database\Sql\20260401_0910_InsertUsers.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Database\Sql\20260412_1500_CreateAnswers.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Database\Sql\20260412_1510_AlterTasks.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Database\Sql\20260413_2130_AlterAssessmentResult.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Database\Sql\20260430_1900_AlterUsers.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Database\Sql\20260430_2000_AlterUser.sql">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
